/*
 * Lightweight, repeatable real-time playtest swarm.
 * Run it against a launched stack with:
 *   PLAYTEST_URL=http://localhost:8080 npm run playtest:realtime
 *
 * This is not a replacement for human sessions. It gives QA agents a fast
 * regression gate for join/presence, bounded movement, collection, chat,
 * cosmetics and the live bug-report queue.
 */
import { io, Socket } from 'socket.io-client';

type Player = { id: string; name: string; x: number; y: number; coins: number };
type Collectible = { id: string; x: number; y: number };
type TestClient = { socket: Socket; player: Player; events: Set<string> };

const baseUrl = process.env.PLAYTEST_URL || 'http://localhost:8080';
const runId = Date.now();
const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

async function fetchWorld(): Promise<Collectible[]> {
  const response = await fetch(`${baseUrl}/api/world`);
  if (!response.ok) throw new Error(`World endpoint returned ${response.status}`);
  const data = await response.json() as { collectibles?: Collectible[] };
  if (!Array.isArray(data.collectibles) || data.collectibles.length < 3) throw new Error('World does not contain enough collectibles');
  return data.collectibles;
}

function connect(label: string): Promise<TestClient> {
  return new Promise((resolve, reject) => {
    const socket = io(baseUrl, { transports: ['websocket'], timeout: 8_000 });
    const events = new Set<string>();
    const timeout = setTimeout(() => {
      socket.disconnect();
      reject(new Error(`${label}: join timed out`));
    }, 10_000);

    socket.on('connect', () => {
      socket.emit('join', {
        id: `qa_${runId}_${label}`,
        name: `QA ${label}`,
        email: null,
        avatarUrl: `https://i.pravatar.cc/100?img=${20 + label.length}`,
      });
    });
    socket.on('item_collected', () => events.add('item_collected'));
    socket.on('chat_message', () => events.add('chat_message'));
    socket.on('hud_update', () => events.add('hud_update'));
    socket.on('shop_success', () => events.add('shop_success'));
    socket.on('playtest_reported', () => events.add('playtest_reported'));
    socket.once('join_success', (data: { player: Player }) => {
      clearTimeout(timeout);
      resolve({ socket, player: data.player, events });
    });
    socket.once('error', (error: { message?: string }) => {
      clearTimeout(timeout);
      socket.disconnect();
      reject(new Error(`${label}: ${error.message || 'socket error'}`));
    });
  });
}

async function moveTo(client: TestClient, target: Collectible): Promise<void> {
  let x = client.player.x;
  let y = client.player.y;
  while (Math.hypot(target.x - x, target.y - y) > 10) {
    const distance = Math.hypot(target.x - x, target.y - y);
    const step = Math.min(180, distance);
    x += ((target.x - x) / distance) * step;
    y += ((target.y - y) / distance) * step;
    client.socket.emit('move', { x, y, status: `QA moving to ${target.id}` });
    await wait(140);
  }
  await wait(250); // lets the server persist the final bounded movement packet
}

async function run(): Promise<void> {
  const world = await fetchWorld();
  const clients = await Promise.all(['alpha', 'bravo', 'charlie'].map(connect));
  const [alpha, bravo, charlie] = clients;

  try {
    await Promise.all([
      moveTo(alpha, world[0]),
      moveTo(bravo, world[1]),
      moveTo(charlie, world[2]),
    ]);

    alpha.socket.emit('collect', { itemId: world[0].id });
    bravo.socket.emit('collect', { itemId: world[1].id });
    charlie.socket.emit('collect', { itemId: world[2].id });
    alpha.socket.emit('chat', { id: `qa_chat_${runId}`, text: 'QA swarm: proximity and chat smoke test', x: world[0].x, y: world[0].y });
    alpha.socket.emit('shop_buy', { itemId: 'hat_cap' });
    alpha.socket.emit('playtest_report', {
      category: 'multiplayer',
      severity: 'idea',
      title: 'Automated real-time playtest heartbeat',
      reproduction: 'Generated by the QA swarm to verify the report queue.',
      diagnostics: { runId, clients: clients.length, source: 'realtimePlaytest' },
    });

    await wait(1_200);
    const assertions = {
      collectionBroadcast: clients.every(client => client.events.has('item_collected')),
      collectorHudUpdated: alpha.events.has('hud_update') && bravo.events.has('hud_update') && charlie.events.has('hud_update'),
      chatBroadcast: clients.every(client => client.events.has('chat_message')),
      cosmeticPurchase: alpha.events.has('shop_success'),
      reportQueued: alpha.events.has('playtest_reported'),
    };
    const failures = Object.entries(assertions).filter(([, passed]) => !passed).map(([name]) => name);
    console.log(JSON.stringify({ runId, baseUrl, assertions, passed: failures.length === 0, failures }, null, 2));
    if (failures.length) process.exitCode = 1;
  } finally {
    clients.forEach(client => client.socket.disconnect());
  }
}

run().catch(error => {
  console.error('[realtime-playtest] failed:', error);
  process.exitCode = 1;
});
